// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasereplication.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import databasereplication.implementation.ObjectBaseDBSettings;
import databasereplication.proxies.Database;

public class EncryptServerPassword extends CustomJavaAction<java.lang.Boolean>
{
	private final IMendixObject DatabaseServer;

	public EncryptServerPassword(
		IContext context,
		IMendixObject _databaseServer
	)
	{
		super(context);
		this.DatabaseServer = _databaseServer;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		IContext context = this.getContext();
		String unEncryptedPass = (String) this.DatabaseServer.getValue(context, Database.MemberNames.DatabasePassword.toString());
		if (unEncryptedPass != null && !"ThisIsConvertedToAnEncryptedPass".equals(unEncryptedPass)) {
			this.DatabaseServer.setValue(context, Database.MemberNames.DatabasePassword_Encrypted.toString(), ObjectBaseDBSettings.encryptString(unEncryptedPass));
			this.DatabaseServer.setValue(context, Database.MemberNames.DatabasePassword.toString(), "ThisIsConvertedToAnEncryptedPass");
		}
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "EncryptServerPassword";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
