// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package databasereplication.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import databasereplication.implementation.DbTypes.ConnectionString;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateJdbcUrl extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use database.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __database;
	private final databasereplication.proxies.Database database;

	public GenerateJdbcUrl(
		IContext context,
		IMendixObject _database
	)
	{
		super(context);
		this.__database = _database;
		this.database = _database == null ? null : databasereplication.proxies.Database.initialize(getContext(), _database);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		return ConnectionString.generate(this.getContext(), database);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateJdbcUrl";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
